### ISSUE TITLE
About Dataset. Can you provide a little train.json or others data formats ? Thank U~

### ISSUE THREAD

**Issue by sev777** [andreabac3/NLP_Semantic_Role_Labeling#2]
Can you provide a little train.json or others data formats ?

**Comment by andreabac3** [comment]
Hi @sev777, 
thank you for your interest in the project.

Regarding to the dataset, it is private and copyright protected you can contact the [SapienzaNLP](https://github.com/SapienzaNLP) organization to ask for the full dataset.

Furthermore, a sample from the dataset is available in the [presentation slide](https://github.com/andreabac3/NLP-Semantic-Role-Labeling/blob/master/presentation_slide_ner_srl.pdf) at page 23.

Let me know how it goes and if I can do anything else to help you.

Sincerely,
Andrea

**Comment by sev777** [comment]
Thank U for your reply,&nbsp;&nbsp;I will keep in touch with you~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Andrea ***@***.***&gt;; 
发送时间: 2021年5月30日(星期天) 下午5:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [andreabac3/NLP-Semantic-Role-Labeling] About Dataset. Can you provide a little train.json or others data formats ? Thank U~ (#2)





 
Hi @sev777,
 thank you for your interest in the project.
 
Regarding to the dataset, it is private and copyright protected you can contact the SapienzaNLP organization to ask for the full dataset.
 
Furthermore, a sample from the dataset is available in the presentation slide at page 23.
 
Let me know how it goes and if I can do anything else to help you.
 
Sincerely,
 Andrea
